### PR TITLE
Mapping profile2resourceClass; updates on oldResourceClass2newResourceClass mapping 

### PR DESCRIPTION
**Pull request by susannehaaf**

### CODE REVIEW

**Review by vronk — CHANGES_REQUESTED** [review]
please correct following:
- separate multi-values with semicolon (;)  not comma (,)
- no whitespace after the separator
- I believe in the end, we decided to have just one general value for all tools and services ("tool service", or "toolService")
- IDSAGD_* profiles we agreed to map to "structuredDataset"
- "not applicable" -> "not-applicable"

**Comment by susannehaaf** [comment]
@vronk I addressed your comments and corrected the respective spots.

**Comment by twagoo** [comment]
I'm not sure if the following has been processed correctly:
* separate multi-values with semicolon (;) not comma (,)

see 4527196c191b78f906a1762bdd656aa83e549744 which introduces commas if I'm not mistaken

Apart from that, we need someone with permission to carry out the pull request. I hope that @wowasa can do this and/or grant someone from the task force write access to this repository.

**Comment by susannehaaf** [comment]
@twagoo Ohoh, sorry. I (hope I) corrected it. 
Other question: Shouldn't profile "WebLichtWebService" be mapped to "tool service" instead of to "web service"?

**Comment by twagoo** [comment]
#23 includes this (via [clarin-eric/VLO-mapping](https://github.com/clarin-eric/VLO-mapping)). Close this pull request?

**Pull request merged**
